import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
const tools = process.env.HC_BROWSER_TOOLS;
if (!tools) throw new Error('Set HC_BROWSER_TOOLS to a directory containing pinned playwright.');
const { chromium } = createRequire(path.join(tools, 'package.json'))('playwright');
const base = process.env.HC_BROWSER_BASE_URL || 'http://127.0.0.1:4173';
const output = process.env.HC_BROWSER_OUTPUT || 'hc/web/browser-evidence';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const failures = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', locale: 'zh-CN', reducedMotion: 'reduce' });
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: base });
  const page = await context.newPage();
  page.on('pageerror', (error) => failures.push(error.message));
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: '今天想完成什么？' }).waitFor();
  await page.screenshot({ path: path.join(output, 'desktop-welcome.png') });
  await page.getByRole('button', { name: /审查代码/ }).click();
  assert.match(await page.getByLabel('消息', { exact: true }).inputValue(), /审查/);
  await page.getByLabel('消息', { exact: true }).fill('尚未连接时保留的草稿');
  await page.locator('.connection-badge').click();
  await page.getByRole('dialog', { name: '连接与设置', exact: true }).waitFor();
  await page.screenshot({ path: path.join(output, 'connection-settings.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.getByLabel('消息', { exact: true }).inputValue(), '尚未连接时保留的草稿');
  assert.equal(await page.evaluate(() => localStorage.length), 0);

  await page.goto(`${base}/e2e/fixture.html`, { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: '复制代码', exact: true }).click();
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /func health/);
  await page.screenshot({ path: path.join(output, 'desktop-conversation.png') });
  const input = page.getByLabel('消息', { exact: true });
  await input.fill('中文输入');
  const before = await page.locator('.message-user').count();
  await input.dispatchEvent('compositionstart');
  await input.dispatchEvent('keydown', { key: 'Enter', keyCode: 229, isComposing: true, bubbles: true });
  assert.equal(await page.locator('.message-user').count(), before);
  await input.dispatchEvent('compositionend');
  await page.waitForTimeout(100);
  await input.press('Shift+Enter');
  assert.equal(await page.locator('.message-user').count(), before);
  await input.fill('继续说明'); await input.press('Enter');
  await page.getByRole('button', { name: '结束当前会话', exact: true }).waitFor();
  assert.equal(await page.locator('.message-user').count(), before + 1);
  await input.fill('回复期间仍可编辑草稿'); await input.press('Enter');
  assert.equal(await page.locator('.message-user').count(), before + 1);
  await page.getByText('已收到。这是组件测试回复。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '结束会话', exact: true }).click();
  await page.getByRole('dialog', { name: '结束当前会话？', exact: true }).waitFor();
  await page.getByRole('button', { name: '继续当前会话', exact: true }).click();
  assert.equal(await input.inputValue(), '回复期间仍可编辑草稿');
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await page.getByRole('heading', { name: '今天想完成什么？', exact: true }).waitFor();
  assert.equal(await page.getByRole('dialog', { name: '结束当前会话？', exact: true }).isVisible(), false);

  await page.goto(`${base}/e2e/fixture.html?scenario=long`, { waitUntil: 'networkidle' });
  await page.locator('.chat-scroll').evaluate((element) => { element.scrollTop = 0; element.dispatchEvent(new Event('scroll')); });
  await page.getByRole('button', { name: '回到最新', exact: true }).waitFor();
  await page.getByRole('button', { name: '回到最新', exact: true }).click();
  await page.waitForFunction(() => {
    const element = document.querySelector('.chat-scroll');
    return element !== null && element.scrollHeight - element.clientHeight - element.scrollTop < 100;
  }, undefined, { timeout: 5000 });

  await page.goto(`${base}/e2e/fixture.html?scenario=offline`, { waitUntil: 'networkidle' });
  await page.getByLabel('消息', { exact: true }).fill('离线草稿');
  assert.equal(await page.getByRole('button', { name: '发送消息', exact: true }).isDisabled(), true);
  await page.screenshot({ path: path.join(output, 'offline-conversation.png') });

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(output, 'mobile-welcome.png') });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name: '展开会话导航', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: '新建对话', exact: true }).isVisible(), true);
  await page.screenshot({ path: path.join(output, 'mobile-sidebar.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('button', { name: '新建对话', exact: true }).isVisible(), false);
  await page.goto(`${base}/e2e/fixture.html`, { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(output, 'mobile-conversation.png') });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({ width: 320, height: 700 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  // Production App (not the synthetic ChatWorkspace): a waiting tab cannot mutate endpoint state.
  const owner = await context.newPage();
  await owner.goto(base, { waitUntil: 'networkidle' });
  await owner.locator('.connection-badge').click();
  await owner.getByRole('dialog', { name: '连接与设置', exact: true }).waitFor();
  const waiting = await context.newPage(); const waitingMutations = []; const waitingSockets = [];
  waiting.on('request', (request) => { if (request.method() === 'POST') waitingMutations.push(new URL(request.url()).pathname); });
  waiting.on('websocket', () => waitingSockets.push('opened'));
  await waiting.goto(base, { waitUntil: 'networkidle' });
  await waiting.getByText(/另一个标签页正在使用此浏览器的安全连接/).waitFor();
  await waiting.locator('.connection-badge').click();
  assert.equal(await waiting.getByRole('dialog', { name: '连接与设置', exact: true }).count(), 0);
  assert.deepEqual(waitingMutations, []); assert.deepEqual(waitingSockets, []);
  await owner.close();
  await waiting.getByText(/另一个标签页正在使用此浏览器的安全连接/).waitFor({ state: 'hidden' });
  await waiting.locator('.connection-badge').click();
  await waiting.getByRole('dialog', { name: '连接与设置', exact: true }).waitFor();
  assert.deepEqual(waitingMutations, []); assert.deepEqual(waitingSockets, []);
  await waiting.close();
  assert.deepEqual(failures, []);
  console.log('HC browser smoke passed: production App tab ownership/handoff, disconnected app, synthetic conversation fixture, IME, copy, draft, explicit close, new chat, scroll and mobile.');
} finally { await browser.close(); }
