// Code generated by mss application template v1.3.7. DO NOT EDIT.

// Package modules composes generated and handwritten business modules.
package modules

import (
	"github.com/mss-boot-ai/harness-platform-monorepo/platform/internal/modules/all"
	"github.com/mss-boot-ai/harness-platform-monorepo/platform/internal/modules/custom"

	"github.com/mss-boot-io/mss-boot-admin/admin/business"
)

// Modules returns generated modules first, followed by explicit custom modules.
func Modules() []business.Module {
	return append(all.Modules(), custom.Modules()...)
}
